# Generated by Django 3.1.12 on 2025-11-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombreAlumno', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombreMaestro', models.CharField(max_length=100)),
                ('telefonoMaestro', models.BigIntegerField()),
            ],
            options={
                'db_table': 'maestro',
            },
        ),
    ]
