# Generated by Django 3.1.12 on 2025-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='calificacion_parcial1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='calificacion_parcial2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='calificacion_parcial3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='promedio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefonoAlumno',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
